[project]
name = "qcluster"
version = "0.1.3"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "pandas>=2.3.0",
    "pandas-stubs==2.2.3.250527",
    "pydantic>=2.11.5",
    "sentence-transformers>=4.1.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]
