name: Coveralls

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    env:
      TOKENIZERS_PARALLELISM: ${{ TOKENIZERS_PARALLELISM }}
      OLLAMA_MODEL: ${{ secrets.OLLAMA_MODEL }}
      OLLAMA_REPORTING_MODEL: ${{ secrets.OLLAMA_REPORTING_MODEL }}
      OLLAMA_HOST: ${{ secrets.OLLAMA_HOST }}
      SENTENCE_TRANSFORMERS_MODEL: ${{ secrets.SENTENCE_TRANSFORMERS_MODEL }}
      EVALUATION_RESULTS_DIR: ${{ secrets.EVALUATION_RESULTS_DIR }}
      EVALUATION_REPORT_PROMPT_TEMPLATE: ${{ secrets.EVALUATION_REPORT_PROMPT_TEMPLATE }}
      DESCRIPTION_PROMPT_TEMPLATE: ${{ secrets.DESCRIPTION_PROMPT_TEMPLATE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync
        shell: bash

      - name: Run tests and generate coverage report
        run: uv run pytest
        shell: bash
        env:
          PYTHONPATH: .:./tests



      - name: Upload coverage reports to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}